- compare_str: 'Sync initial done'
  send_cmd: '[AUTO,ON]'
- compare_str: 'warm reboot, '
  send_cmd: '[AUTO,RANDOM_ATTACH,ON]'
- compare_str: 'DEBUG: FUNC[dump_buf_really ] LINE[427 ]:   60 00 00'
  send_cmd: '[AUTO,REBOOT]'
